### ISSUE TITLE
Old name renamed projects remains

### ISSUE THREAD

**Issue by schoentoon** [lquixada/my-travis#8]
I renamed one of projects on github yesterday. I had to setup travis again as expected. Afterwards my project shows up in my-travis under both the old name and the new name. Only the new name actually leading to the right page. Old name however shows the gray error icon, but this is probably because it error'd out after it received hooks while it was already renamed. Is this an issue on travis-ci's side or on my-travis side?

**Comment by lquixada** [comment]
my-travis consumes the travis api which has some issue with renamed or deleted projects. You can check it out at the url: https://api.travis-ci.org/repos?owner_name[]=<yourusernamehere>

If your old project is there, the problem is on the travis-ci side. Otherwise, I must check what's going on in the extension.

**Comment by schoentoon** [comment]
It is indeed still visible through the api. You happen to have any pointers on how I can get rid of it? Maybe an option to hide certain projects would be nice in my-travis though.

**Comment by lquixada** [comment]
Seems to me that it's much more reasonable to open an issue in the travisci-api repo since other consumers must be going through the same problem! Otherwise I'll have to spend time fixing an issue that will be (hopefully) fixed later on.

**Comment by schoentoon** [comment]
Understandable, I opened an issue about it over at https://github.com/travis-ci/travis-api/issues/59
